language: node_js
cache: yarn
jobs:
  include:
    - stage: "Server Tests"
      node_js: "10"
      services:
        postgresql
      before_script: yarn install && ./scripts/initDb.js test
      script: yarn test
      
    - stage: "Client Tests"
      node_js: "10"
      before_script: cd client && yarn install
      script: yarn test
      script: yarn integration
